import { L, type Localized } from './i18n';
export type ProjectGalleryImage = {src:string;alt:Localized;label:Localized};
export type Project = { id:string; slug:string; title:Localized; area:number; property:'apartment'|'house'; style:'warm'|'contemporary'|'scandinavian'|'natural'; summary:Localized; challenge:Localized; solution:Localized; materials:Localized[]; alts:Localized[]; gallery?:ProjectGalleryImage[]; services:string[]; isConcept:true };
export const styles = { warm:L('Warm minimalism','Teplý minimalismus','Тёплый минимализм'), contemporary:L('Contemporary','Současný styl','Современный'), scandinavian:L('Scandinavian','Skandinávský','Скандинавский'), natural:L('Natural materials','Přírodní materiály','Натуральные материалы') };
export const projects: Project[] = [
 { id:'oak-residence',slug:'the-oak-residence',title:L('The Oak Residence','Dubová rezidence','Дубовая резиденция'),area:86,property:'apartment',style:'warm',isConcept:true,services:['interior-design','furnishing'],summary:L('A softer rhythm of living. Oak, pale stone and tactile fabrics bring warmth to an open, light-filled apartment.','Klidnější rytmus bydlení. Dub, světlý kámen a příjemné textilie vnášejí teplo do otevřeného, prosvětleného bytu.','Спокойный ритм жизни. Дуб, светлый камень и фактурный текстиль добавляют тепла открытому, наполненному светом интерьеру.'),challenge:L('Create a generous shared living space without losing the small, quiet moments. Storage needed to feel like architecture, rather than another piece of furniture.','Vytvořit velkorysý společný prostor, který nabídne i klidné chvíle. Úložné prostory mají být součástí architektury, nikoli dalším kusem nábytku.','Создать просторную общую зону и сохранить место для тихих личных моментов. Хранение должно стать частью архитектуры, а не дополнительной мебелью.'),solution:L('A continuous wall of oak joinery anchors the room. Low furniture keeps daylight moving through the space, while a travertine table gathers the seating into an intimate island. A restrained palette gives every texture room to be noticed.','Souvislá stěna dubového nábytku prostor sjednocuje. Nízký nábytek propouští světlo a travertinový stolek vytváří příjemný střed posezení. Střídmá paleta nechává vyniknout každou texturu.','Встроенная система хранения из дуба вдоль стены задаёт структуру комнаты. Низкая мебель не перекрывает дневной свет, а травертиновый столик собирает зону отдыха в камерную композицию. Сдержанная палитра подчёркивает фактуру каждого материала.'),materials:[L('Natural oak','Přírodní dub','Натуральный дуб'),L('Travertine','Travertin','Травертин'),L('Cream bouclé','Krémové buklé','Кремовое букле')],alts:[L('Cream sofa, oak cabinetry and a travertine table in a sunlit living room.','Krémová pohovka, dubové skříně a travertinový stolek v prosluněném obývacím pokoji.','Кремовый диван, дубовые шкафы и травертиновый столик в солнечной гостиной.'),L('Ceramic vase and travertine table beside the bouclé sofa.','Keramická váza na travertinovém stolku vedle pohovky z buklé.','Керамическая ваза и травертиновый столик рядом с диваном из букле.')] },
 { id:'quiet-city',slug:'quiet-city-apartment',title:L('Quiet City Apartment','Tichý městský byt','Тихая городская квартира'),area:64,property:'apartment',style:'contemporary',isConcept:true,services:['interior-design','full-renovation'],summary:L('City life, turned down a little. Deep green stone and charcoal surfaces create a grounded, quietly expressive interior.','Městský život o něco tišší. Tmavě zelený kámen a antracitové povrchy tvoří klidný, osobitý interiér.','Спокойная сторона городской жизни. Тёмно-зелёный камень и графитовые поверхности создают собранный, выразительный интерьер.'),challenge:L('Give a compact urban apartment a confident identity while making everyday cooking and gathering easy. The kitchen should feel connected, without taking over the whole home.','Dát kompaktnímu městskému bytu vlastní charakter a usnadnit vaření i setkávání. Kuchyň má být propojená se zbytkem domova, ne mu dominovat.','Придать компактной городской квартире характер и сделать готовку и общение удобными. Кухня должна быть частью общего пространства, не перетягивая всё внимание на себя.'),solution:L('A green stone island becomes both a working surface and a place to pause. Handle-free charcoal cabinetry simplifies the visual field; walnut stools and warm light keep the darker palette welcoming. Clear circulation leaves the room feeling larger.','Ostrůvek ze zeleného kamene slouží k práci i odpočinku. Antracitové skříně bez úchytek zklidňují pohled, ořechové stoličky a teplé světlo zútulňují tmavou paletu. Volné průchody opticky zvětšují prostor.','Остров из зелёного камня работает и как рабочая поверхность, и как место для короткой паузы. Графитовые фасады без ручек делают интерьер визуально спокойнее, а ореховые стулья и тёплый свет смягчают тёмную палитру. Свободные проходы усиливают ощущение простора.'),materials:[L('Green stone','Zelený kámen','Зелёный камень'),L('Walnut','Ořech','Орех'),L('Matte charcoal','Matný antracit','Матовый графит')],alts:[L('Charcoal kitchen with a dark green stone island and walnut stools.','Antracitová kuchyň s ostrůvkem z tmavě zeleného kamene a ořechovými stoličkami.','Графитовая кухня с островом из тёмно-зелёного камня и ореховыми стульями.'),L('Green stone island corner, walnut stool and ceramic bowl of pears.','Roh zeleného kamenného ostrůvku, ořechová stolička a keramická mísa s hruškami.','Угол острова из зелёного камня, ореховый стул и керамическая чаша с грушами.')] },
 { id:'soft-light-studio',slug:'studio-in-soft-light',title:L('Studio in Soft Light','Studio v měkkém světle','Студия в мягком свете'),area:38,property:'apartment',style:'scandinavian',isConcept:true,services:['interior-design','furnishing'],summary:L('Small in footprint. Generous in feeling. A light-filled studio finds a place for every part of the day.','Malá plocha, velkorysý pocit. Prosvětlené studio má místo pro každou část dne.','Небольшая площадь, но ощущение простора. В светлой студии нашлось место для сна, работы, готовки и отдыха.'),challenge:L('Bring sleeping, cooking and relaxing into 38 m² without turning the home into a collection of compromises. Privacy and natural light deserve equal attention.','Vměstnat spaní, vaření i odpočinek do 38 m² bez pocitu kompromisu. Soukromí a denní světlo si zaslouží stejnou pozornost.','Объединить сон, готовку и отдых на 38 м² без ощущения компромисса. Приватность и дневной свет одинаково важны.'),solution:L('A pale wood sleeping alcove defines a private retreat without closing off the room. A slatted divider filters views rather than light. Sage cabinetry, integrated storage and linen soften the transition between daily rituals.','Spací nika ze světlého dřeva nabízí soukromí, aniž by uzavřela místnost. Laťová příčka filtruje pohledy, ne světlo. Šalvějová kuchyň, vestavěné úložné prostory a len propojují denní rituály.','Спальная ниша из светлого дерева создаёт приватный уголок, не закрывая комнату. Реечная перегородка скрывает вид, но пропускает свет. Шалфейные фасады, встроенное хранение и льняной текстиль мягко связывают разные сценарии повседневной жизни.'),materials:[L('Pale ash','Světlý jasan','Светлый ясень'),L('Washed linen','Praný len','Мягкий лён'),L('Sage finish','Šalvějový povrch','Шалфейный оттенок')],alts:[L('Compact studio with pale wood sleeping alcove and sage kitchenette.','Kompaktní studio se spací nikou ze světlého dřeva a šalvějovou kuchyňkou.','Компактная студия со спальной нишей из светлого дерева и шалфейной кухней.'),L('Linen bedding, reading light and pale wood slat divider.','Lněné povlečení, čtecí lampa a laťová příčka ze světlého dřeva.','Льняное постельное бельё, лампа для чтения и светлая реечная перегородка.')] },
 { id:'courtyard-home',slug:'courtyard-family-home',title:L('Courtyard Family Home','Rodinný dům se dvorem','Семейный дом с внутренним двором'),area:118,property:'house',style:'natural',isConcept:true,services:['full-renovation','furnishing'],summary:L('Room to gather, space to breathe. An easy-going family home opens its everyday life to a green courtyard.','Místo pro společné chvíle i klid. Neformální rodinný dům propojuje každodenní život se zeleným dvorem.','Место для общих вечеров и достаточно простора, чтобы дышать свободнее. Семейный дом естественно раскрывается в зелёный внутренний двор.'),challenge:L('Create a family space that can move from busy mornings to long, slow dinners. The connection to the courtyard should be present even when the doors are closed.','Vytvořit rodinný prostor pro rušná rána i dlouhé večeře. Spojení se dvorem má zůstat citelné i se zavřenými dveřmi.','Создать семейное пространство, которое одинаково удобно и в суетливое утро, и за долгим неспешным ужином. Связь со двором должна ощущаться даже при закрытых дверях.'),solution:L('The dining table follows the garden view, making the courtyard part of the room. An olive sofa, woven seating and oak bring the outdoor palette inside. Open circulation and robust, tactile surfaces support everyday family life.','Jídelní stůl sleduje výhled do zahrady a dvůr se stává součástí místnosti. Olivová pohovka, výplet a dub přenášejí přírodní paletu dovnitř. Volný pohyb a odolné povrchy vyhovují rodinnému životu.','Обеденный стол развёрнут к саду, поэтому двор воспринимается как продолжение комнаты. Оливковый диван, плетёные кресла и дуб переносят природную палитру внутрь. Свободные проходы и износостойкие фактурные поверхности выдерживают ритм семейной жизни.'),materials:[L('Oiled oak','Olejovaný dub','Промасленный дуб'),L('Woven fibre','Přírodní výplet','Натуральное плетение'),L('Terracotta','Terakota','Терракота')],alts:[L('Olive sofa and oak dining table opening onto a leafy courtyard.','Olivová pohovka a dubový jídelní stůl s výhledem do zeleného dvora.','Оливковый диван и дубовый обеденный стол с видом на зелёный двор.'),L('Terracotta vase and handmade plates on an oak dining table.','Terakotová váza a ručně vyráběné talíře na dubovém jídelním stole.','Терракотовая ваза и тарелки ручной работы на дубовом столе.')] },
];
export const projectGallery=(project:Project):ProjectGalleryImage[]=>project.gallery?.length?project.gallery:project.alts.map((alt,index)=>({src:`/images/projects/${project.id}/${index===0?'cover':index===1?'detail':`gallery-${index+1}`}.png`,alt,label:index===0?L('The whole space','Celý prostor','Общий вид'):index===1?L('The details','Detaily','Детали'):L(`Photo ${index+1}`,`Fotografie ${index+1}`,`Фото ${index+1}`)}));
export const imagePath = (project:Project,image:number|boolean=0) => {const index=typeof image==='boolean'?(image?1:0):image;const gallery=projectGallery(project);return (gallery[index]??gallery[0]).src;};
export const packageNames = {
 Essential:L('Essential','Základ','Базовый'),
 Complete:L('Complete','Kompletní','Полный'),
 Signature:L('Signature','Na míru','Индивидуальный'),
};

export const packageSelectNames = {
 Essential:L('Essential — core renovation','Základ — základní renovace','Базовый — стандартная отделка'),
 Complete:L('Complete — expanded interior scope','Kompletní — rozšířený rozsah','Полный — расширенная отделка'),
 Signature:L('Signature — bespoke solutions','Na míru — individuální řešení','Индивидуальный — сложные решения'),
};

export const packageHighlights = {
 Essential:{
  summary:L('For a calm, functional renovation with standard finishes and straightforward decisions.','Pro klidnou a funkční renovaci se standardními povrchy a jasnými rozhodnutími.','Для аккуратного и функционального ремонта со стандартной отделкой и понятными решениями.'),
  bullets:[
   L('standard finishes','standardní povrchy','стандартная отделка'),
   L('clear material palette','jasná paleta materiálů','понятная палитра материалов'),
   L('without bespoke joinery','bez nábytku na míru','без сложной столярки'),
  ],
 },
 Complete:{
  summary:L('For a more complete interior concept with broader finishes and coordinated decisions across the whole space.','Pro ucelenější interiér s širší škálou povrchů a koordinovanými rozhodnutími napříč celým prostorem.','Для более цельного интерьера с расширенной отделкой и согласованными решениями по всему пространству.'),
  bullets:[
   L('expanded finish scope','rozšířená škála povrchů','расширенная отделка'),
   L('interior coordination','koordinace interiéru','координация интерьера'),
   L('balanced budget / detail ratio','vyvážený poměr ceny a detailu','баланс бюджета и деталей'),
  ],
 },
 Signature:{
  summary:L('For more ambitious spaces with custom elements, richer detailing and a higher level of individualisation.','Pro ambicióznější prostory s prvky na míru, výraznějším detailem a vyšší mírou individualizace.','Для более сложных пространств с индивидуальными элементами, мебелью на заказ и высоким уровнем детализации.'),
  bullets:[
   L('bespoke elements','prvky na míru','индивидуальные элементы'),
   L('custom joinery','nábytek na zakázku','мебель на заказ'),
   L('higher detail level','vyšší míra detailu','более высокий уровень детализации'),
  ],
 },
};

export const packageCopy = {
 Essential:L('Foundational finishes, standard material choices and coordination of the defined works.','Základní povrchy, standardní materiály a koordinace vymezených prací.','Базовая отделка, стандартные материалы и координация согласованных работ.'),
 Complete:L('Expanded finishes, a coordinated interior scheme and detailed material planning.','Rozšířené povrchy, sladěný interiér a podrobný plán materiálů.','Расширенная отделка, согласованная концепция интерьера и подробный подбор материалов.'),
 Signature:L('Complex finishes, bespoke joinery and more detailed coordination of custom elements.','Složitější povrchy, nábytek na míru a podrobná koordinace atypických prvků.','Сложная отделка, индивидуальная столярка и детальная координация заказных элементов.'),
};
export type Service = { slug:string; title:Localized; short:Localized; intro:Localized; image:string; deliverables:Localized[]; excluded:Localized; needs:Localized; cost:Localized };
export const services:Service[] = [
 {slug:'interior-design',title:L('Interior design','Návrh interiéru','Дизайн интерьера'),short:L('Layouts, materials and a complete interior concept.','Dispozice, materiály a ucelený návrh interiéru.','Планировка, материалы и цельная концепция интерьера.'),intro:L('For a new beginning, a difficult layout, or a home that no longer fits. We connect your everyday needs with a coherent spatial and material direction.','Pro nový začátek, složitou dispozici nebo domov, který už nevyhovuje. Propojíme každodenní potřeby s uceleným prostorovým a materiálovým řešením.','Для новой квартиры, сложной планировки или дома, который перестал вам подходить. Мы переводим повседневные потребности в цельную планировку, материалы и атмосферу.'),image:'soft-light-studio/detail',deliverables:[L('A brief rooted in your daily routines','Zadání vycházející z vašeho dne','Бриф, основанный на ваших привычках и сценариях жизни'),L('Layout options and an agreed direction','Varianty dispozice a schválený směr','Варианты планировки и согласованная концепция'),L('Material palette and concept visualisations','Materiálová paleta a vizualizace konceptu','Палитра материалов и концептуальные визуализации'),L('Working drawings for the agreed scope','Pracovní výkresy dle rozsahu','Рабочие чертежи в рамках согласованного объёма')],excluded:L('Construction, purchases, structural engineering and statutory approvals are separate. Concept drawings are not a substitute for a specialist assessment.','Realizace, nákupy, statika a úřední povolení jsou samostatné. Koncepční výkresy nenahrazují odborné posouzení.','Строительство, закупки, инженерные расчёты и официальные согласования — отдельно. Концептуальные чертежи не заменяют обследование специалиста.'),needs:L('An existing plan, a few photographs, your priorities and a list of what should stay. Measurements must be verified before technical work.','Stávající půdorys, několik fotografií, priority a seznam věcí k zachování. Před technickou prací je nutné ověřit rozměry.','План, несколько фотографий, приоритеты и список того, что нужно сохранить. Перед технической работой необходимо проверить размеры.'),cost:L('An individual fee depends on area, complexity and the agreed drawing package. Design-only work is not priced with the full-renovation calculator.','Individuální cena závisí na ploše, složitosti a dohodnuté dokumentaci. Samostatný návrh nepočítáme kalkulátorem celkové renovace.','Индивидуальная стоимость зависит от площади, сложности и состава документации. Калькулятор полного ремонта для отдельного дизайна не применяется.')},
 {slug:'full-renovation',title:L('Full renovation','Kompletní renovace','Ремонт под ключ'),short:L('A coordinated renovation from planning through handover.','Koordinovaná renovace od plánování po předání.','Согласованный ремонт от планирования до приёмки.'),intro:L('For homes ready for a more complete transformation. A defined scope connects design intent, material decisions and the sequence of work.','Pro domovy připravené na zásadnější změnu. Jasný rozsah propojuje návrh, výběr materiálů a postup prací.','Для жилья, которому нужна серьёзная трансформация. Чётко определённый состав работ связывает дизайн, выбор материалов и последовательность ремонта.'),image:'courtyard-home/cover',deliverables:[L('An agreed scope and planning budget','Dohodnutý rozsah a orientační rozpočet','Согласованный объём работ и ориентировочный бюджет'),L('A coordinated sequence of trades','Koordinovaná návaznost řemesel','Согласованная последовательность работ'),L('Material decisions and quality checkpoints','Výběr materiálů a kontrolní body','Выбор материалов и контрольные точки'),L('A documented review and handover','Zdokumentovaná kontrola a předání','Документированная проверка и приёмка')],excluded:L('Structural changes, permits, freestanding furniture, appliances, unforeseen work and taxes are excluded from illustrative calculator ranges.','Konstrukční zásahy, povolení, volný nábytek, spotřebiče, nepředvídané práce a daně nejsou součástí orientační kalkulace.','Конструктивные изменения, разрешения, отдельно стоящая мебель, техника, непредвиденные работы и налоги не входят в демонстрационный расчёт.'),needs:L('Access to the property, available drawings and a clear decision-maker. Existing services, substrate conditions and building rules need checking first.','Přístup do objektu, dostupné výkresy a určený rozhodovatel. Nejprve je nutné ověřit rozvody, podklady a pravidla domu.','Нужны доступ на объект, имеющиеся чертежи и человек, принимающий решения. До начала работ проверяются коммуникации, состояние оснований и правила здания.'),cost:L('Explore an illustrative range with our calculator. A real quote would require a site assessment, verified quantities and an approved specification.','V kalkulátoru si můžete ověřit orientační rozmezí. Skutečná nabídka vyžaduje prohlídku, ověřené výměry a schválenou specifikaci.','Калькулятор покажет ориентировочную стоимость. Для реальной сметы нужны обследование объекта, проверенные объёмы и утверждённая спецификация.')},
 {slug:'furnishing',title:L('Furnishing & styling','Vybavení a styling','Комплектация и декор'),short:L('Furniture, lighting, textiles and decor selected as one system.','Nábytek, osvětlení, textilie a dekor jako jeden celek.','Подбор мебели, света, текстиля и декора как единой системы.'),intro:L('For a finished space that needs the right final layer. Furniture, lighting and textiles are considered together, with scale and everyday use in mind.','Pro hotový interiér, který potřebuje závěrečné doladění. Nábytek, osvětlení a textilie řešíme jako jeden celek s ohledem na proporce a každodenní používání.','Для готового интерьера, которому не хватает завершающих деталей. Мебель, освещение и текстиль подбираются как единая система — с учётом масштаба и реальных сценариев жизни.'),image:'oak-residence/detail',deliverables:[L('Furniture, lighting and textile direction','Směr pro nábytek, světla a textilie','Концепция мебели, света и текстиля'),L('A coordinated selection and specification','Sladěný výběr a specifikace','Согласованный подбор и спецификация'),L('Alternatives approved before substitution','Schválení alternativ před záměnou','Согласование альтернатив до замены'),L('A purchasing and delivery plan','Plán nákupů a dodávek','План закупок и поставок')],excluded:L('Product purchases, third-party delivery charges and installation are not automatically included in the service fee. Stock and lead times need confirmation.','Nákupy produktů, doprava třetích stran a montáž nejsou automaticky součástí honoráře. Dostupnost a termíny je nutné potvrdit.','Покупка товаров, сторонняя доставка и монтаж не включаются в стоимость услуги автоматически. Наличие и сроки требуют подтверждения.'),needs:L('Room dimensions, photographs, your purchasing budget and the pieces you already love. We agree which existing items should be part of the new scheme.','Potřebujeme rozměry místností, fotografie, rozpočet na nákup a věci, které si chcete ponechat. Společně určíme, které stávající prvky zapojíme do nového řešení.','Нужны размеры комнат, фотографии, бюджет на закупки и предметы, которые хочется сохранить. Вместе определим, что войдёт в новую концепцию.'),cost:L('The fee is scoped around the rooms, specification detail and level of coordination. Furniture purchases remain visible as a separate budget.','Honorář vychází z počtu místností, míry podrobnosti specifikace a úrovně koordinace. Samotný nákup nábytku tvoří samostatný rozpočet.','Стоимость зависит от количества комнат, глубины спецификации и объёма координации. Сами покупки мебели и декора учитываются отдельным бюджетом.')},
];
export const steps = [
 {title:L('Listen & define','Pochopit zadání','Понять задачу'),text:L('Your routines, priorities and existing plans become a shared brief. Agree what success means before choosing a finish.','Z vašich návyků, priorit a plánů vznikne společné zadání. Než vybereme povrchy, shodneme se na cíli.','Привычки, приоритеты и исходные планы складываются в общий бриф. До выбора отделки важно согласовать, что будет считаться хорошим результатом.'),decision:L('Approve the brief. Missing drawings or unresolved priorities can change the next steps.','Schvalte zadání. Chybějící výkresy nebo nejasné priority mohou změnit další postup.','Утвердите бриф. Отсутствующие чертежи или неясные приоритеты могут изменить дальнейшие шаги.')},
 {title:L('Shape the idea','Vytvořit koncept','Придать идее форму'),text:L('The brief informs layout options, materials and visual studies. A clear design direction makes later choices easier.','Zadání určuje varianty dispozice, materiály a vizuální koncept. Jasný směr usnadní další rozhodování.','Бриф задаёт варианты планировки, материалы и визуальную концепцию. Чёткое направление упрощает дальнейшие решения.'),decision:L('Choose a layout and palette. Additional options or specialist reviews can extend this stage.','Vyberte dispozici a paletu. Další varianty či odborné posouzení mohou tuto fázi prodloužit.','Выберите планировку и палитру. Дополнительные варианты и проверки специалистов могут продлить этап.')},
 {title:L('Scope & budget','Rozsah a rozpočet','Объём и бюджет'),text:L('The chosen design becomes a documented scope, quantities and material specification. Inclusions and exclusions stay visible.','Vybraný návrh se promění v rozsah, výměry a specifikaci. Zahrnuté i vyloučené práce zůstávají jasné.','Выбранный дизайн становится перечнем работ, объёмов и материалов. Включённые работы и исключения остаются видимыми.'),decision:L('Approve scope and budget before work. Unverified site conditions may require a revision.','Před zahájením schvalte rozsah a rozpočet. Neověřený stav objektu může vyžadovat úpravu.','Утвердите объём работ и бюджет до начала ремонта. Непроверенное состояние объекта может потребовать пересмотра.')},
 {title:L('Bring it together','Uvést do života','Воплотить в жизнь'),text:L('The approved scope guides the sequence of work and material deliveries. Changes are documented with their cost and timing impact.','Schválený rozsah určuje postup prací a dodávky. Změny dokumentujeme včetně dopadu na cenu a termín.','Утверждённый объём задаёт последовательность работ и поставок. Изменения фиксируются вместе с влиянием на цену и сроки.'),decision:L('Approve changes before implementation. Lead times, access and discoveries on site can affect the programme.','Změny schvalujte před provedením. Dodací lhůty, přístup a nálezy na místě mohou ovlivnit harmonogram.','Согласуйте изменения до их выполнения. Сроки поставок, доступ на объект и неожиданные условия на месте могут повлиять на график.')},
 {title:L('Review & settle in','Zkontrolovat a zabydlet se','Проверить и принять работу'),text:L('A joint review checks the work against the agreed scope. Remaining items, care information and relevant documents are gathered together.','Společná kontrola porovná výsledek se zadáním. Zaznamenáme zbývající úkoly, pokyny k péči a dokumenty.','Совместная проверка сверяет результат с согласованным объёмом. Собираются замечания, инструкции по уходу и документы.'),decision:L('Record acceptance and any outstanding items. Corrections and missing deliveries are tracked explicitly.','Zaznamenejte převzetí i nedodělky. Opravy a chybějící dodávky evidujeme samostatně.','Зафиксируйте приёмку и оставшиеся задачи. Исправления и недостающие поставки учитываются отдельно.')},
];
export const serviceFaqs:Record<Service['slug'],[Localized,Localized][]> = {
 'interior-design':[
  [L('What do I receive at the end of the design stage?','Co dostanu na konci návrhu?','Что я получу по итогам дизайн-проекта?'),L('The agreed package can include layout options, the selected concept, material direction, visualisations and working drawings for the defined scope. The exact deliverables are agreed before work starts.','Dohodnutý balíček může zahrnovat dispoziční varianty, vybraný koncept, materiálové řešení, vizualizace a pracovní výkresy v dohodnutém rozsahu. Přesné výstupy se stanoví před začátkem práce.','В согласованный пакет могут входить варианты планировки, выбранная концепция, материалы, визуализации и рабочие чертежи в оговорённом объёме. Точный состав фиксируется до начала работы.')],
  [L('How many layout options are included?','Kolik dispozičních variant je zahrnuto?','Сколько вариантов планировки входит в работу?'),L('The number of options depends on the brief and should be written into the scope. The goal is not to generate endless variants, but to compare meaningful directions and agree one.','Počet variant závisí na zadání a má být uveden v rozsahu služby. Cílem není vytvářet nekonečné množství možností, ale porovnat smysluplné směry a jeden schválit.','Количество вариантов зависит от задачи и должно быть указано в составе услуги. Цель — не бесконечные версии, а несколько осмысленных решений и выбор одного направления.')],
  [L('Are engineering calculations or approvals included?','Jsou součástí statické výpočty nebo povolení?','Входят ли инженерные расчёты и согласования?'),L('No. Concept and working drawings do not replace structural, MEP or statutory specialist work. Those checks are arranged separately when the project requires them.','Ne. Koncepční ani pracovní výkresy nenahrazují statické, technické ani úřední posouzení. Potřebné odborné kontroly se řeší samostatně.','Нет. Концептуальные и рабочие чертежи не заменяют расчёты конструктора, инженеров или официальные согласования. При необходимости они организуются отдельно.')],
  [L('Can I order design without renovation?','Mohu si objednat návrh bez realizace?','Можно заказать только дизайн без ремонта?'),L('Yes. Interior design is a standalone service. You can use the completed package with your own contractor, subject to any specialist checks required for the property.','Ano. Návrh interiéru je samostatná služba. Hotové podklady můžete použít s vlastním dodavatelem, s ohledem na potřebná odborná ověření.','Да. Дизайн интерьера — самостоятельная услуга. Готовую документацию можно передать своему подрядчику с учётом необходимых технических проверок.')],
 ],
 'full-renovation':[
  [L('Is the online estimate a final quote?','Je online odhad konečná nabídka?','Онлайн-калькулятор показывает окончательную смету?'),L('No. It is a planning range. A real quote requires a site visit, verified quantities, an agreed specification and confirmation of exclusions.','Ne. Jde o orientační rozmezí. Skutečná nabídka vyžaduje prohlídku, ověřené výměry, dohodnutou specifikaci a potvrzení výjimek.','Нет. Это ориентир для планирования. Реальная смета требует осмотра объекта, проверенных объёмов, согласованной спецификации и списка исключений.')],
  [L('What happens when the scope changes during the project?','Co se stane, když se během projektu změní rozsah?','Что происходит, если объём работ меняется по ходу ремонта?'),L('The change should be described, priced and approved before the affected work continues. Its effect on timing should be recorded at the same time.','Změna se má popsat, ocenit a schválit před pokračováním dotčených prací. Současně se zaznamená její vliv na termín.','Изменение описывается, оценивается и согласовывается до продолжения затронутых работ. Одновременно фиксируется влияние на сроки.')],
  [L('Are furniture and appliances part of the renovation package?','Je součástí renovace nábytek a spotřebiče?','Мебель и техника входят в ремонт под ключ?'),L('Freestanding furniture and appliances are outside the illustrative renovation range. Furnishing and purchasing can be scoped separately.','Volně stojící nábytek a spotřebiče nejsou součástí orientačního rozsahu renovace. Vybavení a nákupy lze řešit samostatně.','Отдельно стоящая мебель и техника не входят в демонстрационный диапазон ремонта. Комплектацию и закупки можно согласовать отдельно.')],
  [L('When can a reliable schedule be confirmed?','Kdy lze potvrdit spolehlivý harmonogram?','Когда можно подтвердить реальный график работ?'),L('Only after the property, scope, lead times and access constraints have been checked. The portfolio demo intentionally does not promise a fixed duration.','Až po ověření stavu objektu, rozsahu, dodacích lhůt a podmínek přístupu. Portfoliová ukázka záměrně neslibuje pevnou délku.','Только после проверки объекта, объёма работ, сроков поставок и условий доступа. В портфолио-демо намеренно нет обещаний фиксированной длительности.')],
 ],
 'furnishing':[
  [L('Can you work with furniture I already own?','Lze pracovat s nábytkem, který už mám?','Можно сохранить мебель, которая у меня уже есть?'),L('Yes. Existing pieces can be treated as fixed elements and the new selection can be built around their size, colour and practical role.','Ano. Stávající kusy lze brát jako pevné prvky a nový výběr přizpůsobit jejich rozměrům, barvě i funkci.','Да. Существующие предметы можно принять как заданные элементы и подбирать новое окружение с учётом их размера, цвета и функции.')],
  [L('Does the service include buying the products?','Zahrnuje služba samotný nákup produktů?','Входит ли покупка товаров в стоимость услуги?'),L('Not automatically. Selection, specification and purchase coordination are different tasks. Product cost, delivery and installation remain visible as separate items unless explicitly included.','Ne automaticky. Výběr, specifikace a koordinace nákupu jsou různé úkoly. Cena produktů, doprava a montáž zůstávají samostatně, pokud nejsou výslovně zahrnuty.','Не автоматически. Подбор, спецификация и организация закупок — разные задачи. Стоимость товаров, доставка и монтаж учитываются отдельно, если иное не согласовано.')],
  [L('What if a selected product becomes unavailable?','Co když vybraný produkt přestane být dostupný?','Что делать, если выбранного товара больше нет в наличии?'),L('A substitute should be proposed and approved before ordering. The replacement is checked for dimensions, finish, price and compatibility with the rest of the scheme.','Před objednáním se navrhne a schválí náhrada. Kontrolují se rozměry, povrch, cena a návaznost na celý koncept.','До заказа предлагается и согласовывается замена. Проверяются размеры, отделка, цена и совместимость с остальной концепцией.')],
  [L('Can furnishing be done room by room?','Lze vybavení řešit po jednotlivých místnostech?','Можно делать комплектацию по отдельным комнатам?'),L('Yes. The scope can cover selected rooms, but shared materials, lighting temperature and circulation should still be coordinated so the home feels consistent.','Ano. Rozsah může zahrnout jen vybrané místnosti, ale materiály, teplotu světla a návaznosti je vhodné koordinovat pro ucelený výsledek.','Да. Можно работать только с выбранными комнатами, но материалы, температуру света и связи между зонами лучше согласовать, чтобы интерьер оставался цельным.')],
 ],
};

export const faqs:[Localized,Localized][] = [
 [L('Can I start with design only?','Mohu začít jen návrhem?','Можно начать только с дизайна?'),L('Yes. Interior design is a separate service with its own agreed deliverables. You do not need to choose a full renovation package.','Ano. Návrh interiéru je samostatná služba s dohodnutými výstupy. Balíček kompletní renovace není nutný.','Да. Дизайн интерьера — отдельная услуга со своим набором материалов и результатов. Выбирать пакет полного ремонта не нужно.')],
 [L('Is the calculator a final quote?','Je kalkulace konečná nabídka?','Калькулятор показывает окончательную смету?'),L('No. It is a reproducible planning example in USD. A real quote requires a site assessment, measured quantities and an agreed specification.','Ne. Jde o orientační výpočet v USD podle pevně dané demo formule. Skutečná nabídka vyžaduje prohlídku, ověřené výměry a dohodnutou specifikaci.','Нет. Это ориентировочный расчёт в USD по фиксированной демонстрационной формуле. Для реальной сметы нужны обследование объекта, проверенные объёмы и согласованная спецификация.')],
 [L('What happens if the scope changes?','Co když se rozsah změní?','Что, если объём работ изменится?'),L('A change should be described, priced and approved with its timing impact before the affected work starts. Keep decisions in writing.','Změnu je třeba popsat, ocenit a schválit včetně dopadu na termín před zahájením dotčených prací. Rozhodnutí zaznamenejte písemně.','Изменение нужно описать, оценить и согласовать вместе с влиянием на сроки до начала затронутых работ. Решения фиксируются письменно.')],
 [L('Are furniture and appliances included?','Je zahrnut nábytek a spotřebiče?','Мебель и техника включены?'),L('Freestanding furniture and appliances are excluded from the renovation calculator. Furnishing has a separate selection and purchasing scope.','Volně stojící nábytek a spotřebiče kalkulátor nezahrnuje. Vybavení má samostatný rozsah výběru a nákupu.','Отдельно стоящая мебель и техника не входят в расчёт ремонта. Для мебели и комплектации предусмотрен отдельный сценарий подбора и закупки.')],
 [L('How long would a renovation take?','Jak dlouho trvá renovace?','Сколько занимает ремонт?'),L('A reliable programme follows a verified scope, property assessment and supplier checks. This concept does not promise fixed delivery dates.','Spolehlivý harmonogram lze sestavit až z ověřeného rozsahu, prohlídky objektu a dostupnosti dodávek. Tato ukázka neslibuje pevné termíny.','Надёжный график можно составить только после проверки объёма работ, состояния объекта и доступности поставок. Демонстрационный проект не обещает фиксированных сроков.')],
 [L('Will my demo enquiry be sent?','Odešle se ukázková poptávka?','Демо-заявка действительно отправляется?'),L('No. FORMA is a fictional portfolio studio. The form runs locally in your browser and never sends an enquiry. Please use sample details.','Ne. FORMA je fiktivní studio vytvořené pro portfolio. Formulář běží v prohlížeči a nic neodesílá. Použijte testovací údaje.','Нет. FORMA — вымышленная студия для портфолио. Форма работает в браузере и ничего не отправляет. Используйте тестовые данные.')],
];
export const contentRepository = { getProjects:()=>projects, getProject:(slug:string)=>projects.find(p=>p.slug===slug), getServices:()=>services, getService:(slug:string)=>services.find(s=>s.slug===slug) };
