'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {calculate,defaults,money,normalizeInput,pricing,PRICING_VERSION,type EstimateInput,type Package} from '@/lib/pricing';
import {packageCopy,packageHighlights,packageNames,packageSelectNames,projects} from '@/lib/content';
import {L,t,type Locale} from '@/lib/i18n';
import {useProject,type SavedEstimate} from './state';
import {Icon} from './icons';
import {ProjectCard} from './projects';
export function Price({input,locale}:{input:EstimateInput;locale:Locale}){const result=calculate(input);return result?<span className="price" data-low={result.low} data-high={result.high}>{money(result.low,locale)} <span className="range-dash">–</span> {money(result.high,locale)}</span>:<span className="manual-message">{t(locale,'manual')}</span>;}
function AreaField({input,setInput,locale,prefix}:{input:EstimateInput;setInput:(v:EstimateInput)=>void;locale:Locale;prefix:string}){return <div className="area-control"><label htmlFor={`${prefix}-area`}>{t(locale,'area')}<span className="area-number"><input id={`${prefix}-area`} type="number" inputMode="decimal" value={Number.isNaN(input.area)?'':input.area} onChange={e=>setInput({...input,area:e.target.value===''?NaN:Number(e.target.value)})} aria-describedby={`${prefix}-hint`}/> m²</span></label><input aria-label={`${t(locale,'area')} · ${L('slider','posuvník','ползунок')[locale]}`} type="range" min="30" max="150" step="1" value={Number.isFinite(input.area)?Math.max(30,Math.min(150,input.area)):30} onChange={e=>setInput({...input,area:Number(e.target.value)})}/><div id={`${prefix}-hint`} className="range-labels"><span>30 m²</span><span>150 m²</span></div></div>;}
export function QuickEstimate({locale}:{locale:Locale}){const [input,setInput]=useState(defaults);const meta=packageHighlights[input.package];const valid=calculate(input);return <div className="quick-estimate"><div><AreaField input={input} setInput={setInput} locale={locale} prefix="quick"/><label className="field">{t(locale,'package')}<select value={input.package} onChange={e=>setInput({...input,package:e.target.value as Package})}>{(Object.keys(pricing) as Package[]).map(p=><option key={p} value={p}>{packageSelectNames[p][locale]}</option>)}</select></label></div><div className="quick-result"><span className="eyebrow">{t(locale,'illustrative')} · USD</span><div className="price-change" key={`${input.area}-${input.package}`}><Price input={input} locale={locale}/></div>{valid&&<div className="quick-package-panel"><div className="quick-package-header"><strong>{packageNames[input.package][locale]}</strong><span>{L('What this package means','Co tento balíček znamená','Что означает этот пакет')[locale]}</span></div><p>{meta.summary[locale]}</p><ul className="quick-package-bullets">{meta.bullets.map((item,i)=><li key={i}>{item[locale]}</li>)}</ul></div>}<Link className="button" href={valid?`/${locale}/estimate?area=${input.area}&package=${input.package}`:`/${locale}/contact?mode=detailed`}>{t(locale,valid?'viewEstimate':'manualCta')}<Icon name="arrow"/></Link></div></div>;}
export function EstimateSummary({input,locale,date}:{input:EstimateInput;locale:Locale;date?:string}){return <div className="estimate-summary"><span className="eyebrow">{t(locale,'illustrative')} · USD</span><Price input={input} locale={locale}/><dl className="summary-facts"><div><dt>{t(locale,'property')}</dt><dd>{t(locale,input.property)}</dd></div><div><dt>{t(locale,'area')}</dt><dd>{input.area} m²</dd></div><div><dt>{t(locale,'condition')}</dt><dd>{t(locale,input.condition)}</dd></div><div><dt>{t(locale,'package')}</dt><dd>{packageNames[input.package][locale]}</dd></div><div><dt>{t(locale,'start')}</dt><dd>{t(locale,input.start)}</dd></div></dl><h3>{t(locale,'included')}</h3><p>{packageCopy[input.package][locale]}</p><p className="small-text">{t(locale,'rangeNote')}</p><p className="small-text">{t(locale,'exclusions')}</p><p className="small-text">{t(locale,'assumption')}</p><div className="formula-note">FORMA · {PRICING_VERSION} · {date?new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(date)):new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date())}</div></div>;}
export function Estimator({locale}:{locale:Locale}){
 const store=useProject(),query=useSearchParams(),heading=useRef<HTMLHeadingElement>(null);const [step,setStep]=useState(0),[saved,setSaved]=useState(false);const applied=useRef('');const queryKey=query.toString();
 useEffect(()=>{if(!store.ready||applied.current===queryKey+'!')return;applied.current=queryKey+'!';if(query.size){const raw=Object.fromEntries(query.entries());store.setDraft(normalizeInput({...store.draft,...raw}));}if(query.get('step')==='result')setStep(3);},[store,query,queryKey]);
 const input=store.draft;const setInput=(v:EstimateInput)=>{store.setDraft(v);setSaved(false);};
 function go(n:number){setStep(n);setTimeout(()=>heading.current?.focus(),0);}
 return <div className="calculator-layout"><div className="calculator-main"><ol className="stepper">{(['object','scope','preferences','result'] as const).map((key,i)=><li key={key} className={step===i?'current':step>i?'done':''}><button onClick={()=>go(i)} aria-current={step===i?'step':undefined}>{step>i&&<Icon name="check"/>}{t(locale,key)}</button></li>)}</ol><div className="calculator-step"><h2 ref={heading} tabIndex={-1}>{t(locale,(['object','scope','preferences','result'] as const)[step])}</h2>{query.has('project')&&<p className="notice">{t(locale,'assumption')} {projects.find(p=>p.id===query.get('project'))?.title[locale]}</p>}
 {step===0&&<><fieldset><legend>{t(locale,'property')}</legend><div className="choice-row">{(['apartment','house'] as const).map(v=><label className={`choice ${input.property===v?'selected':''}`} key={v}><input type="radio" name="property" checked={input.property===v} onChange={()=>setInput({...input,property:v})}/>{t(locale,v)}</label>)}</div></fieldset><AreaField input={input} setInput={setInput} locale={locale} prefix="full"/><label className="field">{t(locale,'condition')}<select value={input.condition} onChange={e=>setInput({...input,condition:e.target.value as EstimateInput['condition']})}>{(['shell','updating','extensive'] as const).map(v=><option key={v} value={v}>{t(locale,v)}</option>)}</select></label>{!calculate(input)&&<div className="notice">{t(locale,'manual')}<Link href={`/${locale}/contact?mode=detailed`}>{t(locale,'manualCta')} →</Link></div>}</>}
 {step===1&&<><div className="scope-context"><span>{L('Calculated for','Počítáno pro','Расчёт для')[locale]}</span><strong>{t(locale,input.property)} · {input.area} m² · {t(locale,input.condition)}</strong><button type="button" className="text-button" onClick={()=>go(0)}>{L('Change','Upravit','Изменить')[locale]}</button></div><fieldset className="packages"><legend className="sr-only">{t(locale,'package')}</legend>{(Object.keys(pricing) as Package[]).map(p=>{const option=calculate({...input,package:p});const meta=packageHighlights[p];return <label className={`package-card ${input.package===p?'selected':''}`} key={p}><input type="radio" name="package" value={p} checked={input.package===p} onChange={()=>setInput({...input,package:p})}/><div className="package-card-body"><div className="package-card-top"><div><h3>{packageNames[p][locale]}</h3><span className="package-card-subtitle">{packageSelectNames[p][locale].replace(`${packageNames[p][locale]} — `,'')}</span></div>{option&&<strong className="package-total">{money(option.low,locale)} <span>–</span> {money(option.high,locale)}</strong>}</div><p>{meta.summary[locale]}</p><ul className="package-inline-features">{meta.bullets.map((item,i)=><li key={i}>{item[locale]}</li>)}</ul><span className="package-rate">{L('Base rate before object and condition factors','Základní sazba před koeficienty objektu a stavu','Базовая ставка до коэффициентов типа и состояния')[locale]}: {money(pricing[p][0],locale)}–{money(pricing[p][1],locale)} / m²</span></div></label>})}</fieldset><div className="notice"><strong>{t(locale,'onlyDesign')}</strong><p>{t(locale,'onlyDesignNote')}</p><Link href={`/${locale}/services/interior-design`}>{L('Interior design','Návrh interiéru','Дизайн интерьера')[locale]} →</Link><Link href={`/${locale}/services/furnishing`}>{L('Furnishing','Vybavení','Комплектация')[locale]} →</Link></div></>}
 {step===2&&<><label className="field">{t(locale,'start')}<select value={input.start} onChange={e=>setInput({...input,start:e.target.value as EstimateInput['start']})}>{(['exploring','soon','later','future'] as const).map(v=><option key={v} value={v}>{t(locale,v)}</option>)}</select></label><label className="field">{t(locale,'notes')}<textarea maxLength={1500} rows={5} value={store.notes} onChange={e=>store.setNotes(e.target.value)}/></label><p className="small-text">{t(locale,'preferenceNote')}</p></>}
 {step===3&&(calculate(input)?<><EstimateSummary input={input} locale={locale}/><div className="button-row no-print"><button className="button" onClick={()=>{store.saveEstimate(input);setSaved(true);}}><Icon name={saved?'check':'bookmark'}/>{t(locale,saved?'estimateSaved':'saveEstimate')}</button><button className="button secondary" onClick={()=>window.print()}>{t(locale,'print')}</button></div><Link className="text-link no-print" onClick={()=>store.saveEstimate(input)} href={`/${locale}/contact?mode=detailed&context=estimate`}>{t(locale,'discuss')} <Icon name="arrow"/></Link></>:<div className="notice">{t(locale,'manual')}<Link className="button" href={`/${locale}/contact?mode=detailed`}>{t(locale,'manualCta')}</Link></div>)}
 </div><div className="step-controls no-print"><button className="text-button" disabled={step===0} onClick={()=>go(step-1)}>← {t(locale,'back')}</button>{step<3?<button className="button" disabled={!calculate(input)} onClick={()=>go(step+1)}>{t(locale,step===2?'viewEstimate':'continue')}<Icon name="arrow"/></button>:<button className="text-button" onClick={()=>go(0)}>{t(locale,'edit')}</button>}</div>{store.unavailable&&<p role="status" className="notice">{t(locale,'storageUnavailable')}</p>}</div><aside className="calculator-aside no-print"><span className="eyebrow">FORMA / {t(locale,'illustrative')}</span><div className="architect-mark" aria-hidden="true"><span/><span/><span/></div><h3>{L('Plan the scope before the spend.','Nejdřív rozsah, potom rozpočet.','Сначала объём работ, потом бюджет.')[locale]}</h3><p>{L('Four steps produce a planning range from the area, property type, condition and package. No contact details are required.','Čtyři kroky vytvoří orientační rozmezí podle plochy, typu objektu, stavu a balíčku. Kontaktní údaje nejsou potřeba.','Четыре шага дают ориентировочный диапазон по площади, типу объекта, состоянию и пакету. Контактные данные не нужны.')[locale]}</p><div className="aside-rule"/><p className="small-text">{t(locale,'rangeNote')}</p><Link className="text-link" href={`/${locale}/process`}>{t(locale,'process')}<Icon name="arrow"/></Link></aside></div>;
}
function SavedResult({value,locale}:{value:SavedEstimate;locale:Locale}){const store=useProject();return <section className="saved-result"><h2>{t(locale,'savedEstimate')}</h2>{value.version!==PRICING_VERSION?<div className="notice"><p>{t(locale,'stale')}</p><button className="button" onClick={()=>store.saveEstimate(value.input)}>{t(locale,'refresh')}</button></div>:<><EstimateSummary input={value.input} locale={locale} date={value.date}/><div className="button-row no-print"><Link className="button" href={`/${locale}/contact?mode=detailed&context=estimate`}>{t(locale,'discuss')}<Icon name="arrow"/></Link><button className="button secondary" onClick={()=>window.print()}>{t(locale,'print')}</button><Link className="text-link" onClick={()=>store.setDraft(value.input)} href={`/${locale}/estimate`}>{t(locale,'edit')} →</Link></div></>}</section>;}
export function MyProject({locale}:{locale:Locale}){const store=useProject(),saved=projects.filter(p=>store.ids.includes(p.id));return <><div className="collection-toolbar"><p>{t(locale,'browserOnly')}</p><button className="text-button" onClick={store.clear}>{t(locale,'clearProject')} ×</button></div>{store.unavailable&&<p role="status" className="notice">{t(locale,'storageUnavailable')}</p>}{saved.length?<div className="project-grid">{saved.map(p=><ProjectCard project={p} locale={locale} key={p.id}/>)}</div>:<div className="empty-state"><Icon name="bookmark"/><h2>{t(locale,'emptySaved')}</h2><div className="button-row"><Link className="button" href={`/${locale}/projects`}>{t(locale,'explore')}<Icon name="arrow"/></Link><Link className="text-link" href={`/${locale}/estimate`}>{t(locale,'plan')} →</Link></div></div>}{store.estimate?<SavedResult value={store.estimate} locale={locale}/>:<div className="notice no-print"><Link href={`/${locale}/estimate`}>{t(locale,'plan')} →</Link></div>}</>;}
