'use client';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Suspense,useEffect,useRef,useState } from 'react';
import { isLocale,locales,t,type Locale } from '@/lib/i18n';
import { services } from '@/lib/content';
import { useProject } from './state';
import { Icon } from './icons';
export function Settings({locale}:{locale:Locale}){
 const path=usePathname(),query=useSearchParams(),router=useRouter();const[theme,setTheme]=useState('system');
 useEffect(()=>{try{const v=localStorage.getItem('forma-theme');if(v&&['light','dark','system'].includes(v))setTheme(v);}catch{}},[]);
 function changeTheme(value:string){setTheme(value);try{localStorage.setItem('forma-theme',value);}catch{}document.documentElement.dataset.preference=value;document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;}
 return <div className="settings"><label><span className="sr-only">{t(locale,'language')}</span><select aria-label={t(locale,'language')} value={locale} onChange={e=>{const segments=path.split('/');segments[1]=e.target.value;router.push(segments.join('/')+(query.size?`?${query}`:''),{scroll:false});}}>{locales.map(l=><option key={l} value={l}>{({en:'EN',cs:'CS',ru:'RU'})[l]}</option>)}</select></label><label className="theme-select"><Icon name="sun"/><span className="sr-only">{t(locale,'theme')}</span><select aria-label={t(locale,'theme')} value={theme} onChange={e=>changeTheme(e.target.value)}>{(['light','dark','system'] as const).map(v=><option value={v} key={v}>{t(locale,v)}</option>)}</select></label></div>;
}
export function Header(){
 const path=usePathname(),candidate=path.split('/')[1],locale=isLocale(candidate)?candidate:'en';const{ids}=useProject();const[servicesOpen,setServicesOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null),menuButton=useRef<HTMLButtonElement>(null),servicesRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{document.documentElement.lang=locale;dialog.current?.close();document.body.style.overflow='';},[path,locale]);
 useEffect(()=>{function outside(e:PointerEvent){if(!servicesRef.current?.contains(e.target as Node))setServicesOpen(false);}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 const links=[['projects','projects'],['process','process'],['journal','journal']] as const;
 const navLink=(href:string,label:string)=><Link key={href} href={`/${locale}/${href}`} className={path.includes(`/${href}`)?'active':''} aria-current={path.includes(`/${href}`)?'page':undefined}>{label}</Link>;
 function close(){dialog.current?.close();document.body.style.overflow='';menuButton.current?.focus();}
 return <><a className="skip-link" href="#main">{t(locale,'skip')}</a><header className="header"><div className="header-inner"><Link className="logo" href={`/${locale}`} aria-label={`FORMA · ${t(locale,'home')}`}>FORMA</Link><nav className="desktop-nav" aria-label={t(locale,'menu')}>{navLink('projects',t(locale,'projects'))}<div className="services-menu" ref={servicesRef} onKeyDown={e=>{if(e.key==='Escape'){setServicesOpen(false);(servicesRef.current?.querySelector('button') as HTMLButtonElement)?.focus();}}}><button className={path.includes('/services')?'active':''} aria-expanded={servicesOpen} aria-controls="services-dropdown" onClick={()=>setServicesOpen(!servicesOpen)}>{t(locale,'services')}<Icon name="chevron"/></button>{servicesOpen&&<div id="services-dropdown" className="dropdown"><Link onClick={()=>setServicesOpen(false)} href={`/${locale}/services`}>{t(locale,'services')} <Icon name="arrow"/></Link>{services.map(s=><Link onClick={()=>setServicesOpen(false)} key={s.slug} href={`/${locale}/services/${s.slug}`}>{s.title[locale]}</Link>)}</div>}</div>{links.slice(1).map(([href,key])=>navLink(href,t(locale,key)))}</nav><div className="header-actions"><div className="desktop-settings"><Suspense><Settings locale={locale}/></Suspense></div><Link href={`/${locale}/my-project`} className="saved-nav" aria-label={`${t(locale,'myProject')} (${ids.length})`}><Icon name="bookmark"/>{ids.length>0&&<span>{ids.length}</span>}</Link><Link className="button small header-cta" href={`/${locale}/estimate`}>{t(locale,'plan')}<Icon name="arrow"/></Link><button ref={menuButton} className="icon-button mobile-toggle" aria-label={t(locale,'menu')} onClick={()=>{dialog.current?.showModal();document.body.style.overflow='hidden';}}><Icon name="menu"/></button></div></div><dialog ref={dialog} className="mobile-menu" aria-label={t(locale,'menu')} onClose={()=>{document.body.style.overflow='';menuButton.current?.focus();}} onClick={e=>{if(e.target===dialog.current)close();}}><div className="menu-top"><span className="logo">FORMA</span><button className="icon-button" onClick={close} aria-label={t(locale,'close')}><Icon name="close"/></button></div><nav>{(['projects','services','process','journal','about','contact'] as const).map(key=><Link onClick={close} key={key} href={`/${locale}/${key}`}>{t(locale,key)}<Icon name="arrow"/></Link>)}</nav><Suspense><Settings locale={locale}/></Suspense><Link onClick={close} className="button" href={`/${locale}/estimate`}>{t(locale,'plan')}<Icon name="arrow"/></Link><p className="small-text">{t(locale,'footerNote')}</p></dialog></header></>;
}
