'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {projects,styles,imagePath,type Project} from '@/lib/content';
import {L,t,type Locale} from '@/lib/i18n';
import {useProject} from './state';
import {Icon} from './icons';
export function SaveButton({id,locale,text=false}:{id:string;locale:Locale;text?:boolean}){const {ids,toggle}=useProject();const saved=ids.includes(id);const [notice,setNotice]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);function handleSave(){const willSave=!saved;toggle(id);setNotice(willSave?L('Added to My project','Přidáno do Mého projektu','Добавлено в «Мой проект»')[locale]:L('Removed from My project','Odebráno z Mého projektu','Удалено из «Моего проекта»')[locale]);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),2200);}return <><button className={`save-button ${saved?'is-saved':''} ${text?'with-text':''}`} aria-label={t(locale,saved?'saved':'save')} aria-pressed={saved} onClick={handleSave}><Icon name={saved?'check':'bookmark'}/>{text&&t(locale,saved?'saved':'save')}</button>{notice&&<div className="save-toast" role="status"><Icon name={saved?'check':'bookmark'}/><span>{notice}</span></div>}</>;}
export function ProjectCard({project,locale}:{project:Project;locale:Locale}){const [imageIndex,setImageIndex]=useState(0);const detail=imageIndex===1;return <article className="project-card"><div className="card-image"><Link href={`/${locale}/projects/${project.slug}`} aria-label={`${t(locale,'viewProject')}: ${project.title[locale]}`}><Image key={`${project.id}-${imageIndex}`} className="project-card-image" src={imagePath(project,detail)} alt={project.alts[imageIndex][locale]} width={1536} height={1024} sizes="(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 33vw"/></Link><SaveButton id={project.id} locale={locale}/><div className="card-image-controls" aria-label={t(locale,'gallery')}><button type="button" className="card-image-arrow previous" onClick={()=>setImageIndex(v=>v?0:1)} aria-label={t(locale,'previous')}><Icon name="arrow"/></button><span aria-live="polite">{imageIndex+1} / 2</span><button type="button" className="card-image-arrow" onClick={()=>setImageIndex(v=>v?0:1)} aria-label={t(locale,'nextImage')}><Icon name="arrow"/></button></div></div><div className="card-heading"><h3><Link href={`/${locale}/projects/${project.slug}`}>{project.title[locale]}</Link></h3><Icon name="arrow"/></div><p className="card-meta">{project.area} m² <span>·</span> {styles[project.style][locale]}</p></article>;}
export function Catalogue({locale}:{locale:Locale}){const query=useSearchParams(),router=useRouter(),path=usePathname();const property=['apartment','house'].includes(query.get('property')||'')?query.get('property')!:'all',size=['compact','medium','spacious'].includes(query.get('size')||'')?query.get('size')!:'all',style=Object.hasOwn(styles,query.get('style')||'')?query.get('style')!:'all';const filtered=projects.filter(p=>(property==='all'||p.property===property)&&(style==='all'||p.style===style)&&(size==='all'||(size==='compact'?p.area<50:size==='medium'?p.area>=50&&p.area<=90:p.area>90)));
 function update(key:string,value:string){const params=new URLSearchParams(query);if(value==='all')params.delete(key);else params.set(key,value);router.push(`${path}${params.size?'?'+params:''}`,{scroll:false});}
 return <><div className="filters"><label>{t(locale,'property')}<select value={property} onChange={e=>update('property',e.target.value)}>{(['all','apartment','house'] as const).map(x=><option value={x} key={x}>{t(locale,x)}</option>)}</select></label><label>{t(locale,'area')}<select value={size} onChange={e=>update('size',e.target.value)}>{(['all','compact','medium','spacious'] as const).map(x=><option value={x} key={x}>{t(locale,x)}</option>)}</select></label><label>{t(locale,'style')}<select value={style} onChange={e=>update('style',e.target.value)}><option value="all">{t(locale,'all')}</option>{Object.entries(styles).map(([key,label])=><option key={key} value={key}>{label[locale]}</option>)}</select></label><button className="text-button" onClick={()=>router.push(path,{scroll:false})}>{t(locale,'clear')} <span aria-hidden="true">×</span></button></div><div className="result-count" aria-live="polite">{filtered.length} {t(locale,'results')}{[property,size,style].some(v=>v!=='all')&&<span className="active-filters">{[property!=='all'?t(locale,property as 'apartment'|'house'):'',size!=='all'?t(locale,size as 'compact'|'medium'|'spacious'):'',style!=='all'?styles[style as keyof typeof styles][locale]:''].filter(Boolean).join(' / ')}</span>}</div>{filtered.length?<div className="project-grid">{filtered.map(p=><ProjectCard key={p.id} project={p} locale={locale}/>)}</div>:<div className="empty-state"><Icon name="bookmark"/><h2>{t(locale,'noResults')}</h2><button className="button" onClick={()=>router.push(path)}>{t(locale,'resetFilters')}</button></div>}</>;
}
export function Gallery({project,locale}:{project:Project;locale:Locale}){const [index,setIndex]=useState(0),[opened,setOpened]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(opened){document.body.style.overflow='hidden';}return()=>{document.body.style.overflow='';};},[opened]);
 function open(i:number,event:React.MouseEvent<HTMLButtonElement>){setIndex(i);setOpened(true);trigger.current=event.currentTarget;dialog.current?.showModal();}
 return <><div className="project-gallery">{[0,1].map(i=><figure key={i}><button onClick={e=>open(i,e)} aria-label={`${t(locale,'gallery')}: ${t(locale,i?'detail':'overview')}`}><Image src={imagePath(project,!!i)} alt={project.alts[i][locale]} width={1536} height={1024} sizes={i?'(max-width: 700px) 100vw, 55vw':'100vw'} priority={!i}/><span className="expand-image"><Icon name="plus"/></span></button><figcaption>{t(locale,i?'detail':'overview')}</figcaption></figure>)}</div><dialog ref={dialog} className="lightbox" aria-label={`${project.title[locale]} · ${t(locale,'gallery')}`} onClose={()=>{setOpened(false);trigger.current?.focus();}} onClick={e=>{if(e.target===dialog.current)dialog.current?.close();}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();setIndex(v=>1-v);}}}><div className="lightbox-top"><span>{project.title[locale]}</span><button className="icon-button" aria-label={t(locale,'close')} onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div>{/* Larger image is mounted only while gallery has been activated. */}{opened&&<Image src={imagePath(project,!!index)} alt={project.alts[index][locale]} width={1536} height={1024} sizes="95vw" quality={85}/>}<div className="lightbox-bottom"><button className="icon-button rotate" onClick={()=>setIndex(1-index)} aria-label={t(locale,'previous')}><Icon name="arrow"/></button><p aria-live="polite">{index+1} / 2 · {project.alts[index][locale]}</p><button className="icon-button" onClick={()=>setIndex(1-index)} aria-label={t(locale,'nextImage')}><Icon name="arrow"/></button></div></dialog></>;
}
